### ISSUE TITLE
Problem with making the video

### ISSUE THREAD

**Issue by PanAdasiekk** [Shynee1/TiktokVideoCreator#1]
I have this problem and i dunno what to do  

Successfully saved audio to outputs/audios/audio0.mp3
Traceback (most recent call last):
  File "C:\Users\Dadasiek\Desktop\TiktokVideoCreator\src\main.py", line 42, in <module>
    comp = creator.create_composition(background_video_path, background_audio_path, audio_destination)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dadasiek\Desktop\TiktokVideoCreator\src\video_creator.py", line 76, in create_composition
    background_video = self.get_backgroud_video(video_background_folder, tts.duration)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dadasiek\Desktop\TiktokVideoCreator\src\video_creator.py", line 20, in get_backgroud_video
    start = random.randint(0, int(video.duration - audio_duration))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dadasiek\AppData\Local\Programs\Python\Python311\Lib\random.py", line 362, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dadasiek\AppData\Local\Programs\Python\Python311\Lib\random.py", line 345, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, -59, -59)

**Comment by Shynee1** [comment]
Thanks for the issue. Did you add the background gameplay files from google drive? Instructions are on the Readme.
